services:
  - type: web
    name: village-identification-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: village-mongodb
          property: connectionString

databases:
  - name: village-mongodb
    databaseName: village_identification
    user: village_user
    region: oregon
    plan: free
